//! Deterministic construction and resource-cost foundation.
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct ResourceCost{pub wood:u32,pub stone:u32,pub metal:u32,pub energy:u32}
#[derive(Clone,Copy,Debug,Default,PartialEq,Eq)]pub struct ResourceStock{pub wood:u32,pub stone:u32,pub metal:u32,pub energy:u32}
impl ResourceStock{pub fn can_afford(&self,c:ResourceCost)->bool{self.wood>=c.wood&&self.stone>=c.stone&&self.metal>=c.metal&&self.energy>=c.energy}pub fn spend(&mut self,c:ResourceCost)->bool{if !self.can_afford(c){return false}self.wood-=c.wood;self.stone-=c.stone;self.metal-=c.metal;self.energy-=c.energy;true}}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct ConstructionDefinition{pub id:&'static str,pub cost:ResourceCost,pub width_mm:u32,pub depth_mm:u32,pub height_mm:u32,pub required_technology:Option<&'static str>}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct ConstructionInstance{pub definition:&'static str,pub position_mm:[i32;3],pub health:u16}
#[derive(Clone,Debug,Default,PartialEq,Eq)]pub struct ConstructionSite{pub structures:Vec<ConstructionInstance>}
impl ConstructionSite{pub fn build(&mut self,d:ConstructionDefinition,p:[i32;3],s:&mut ResourceStock,r:&[&str])->bool{if d.required_technology.is_some_and(|t|!r.contains(&t))||p[0]<0||p[2]<0||!s.spend(d.cost){return false}self.structures.push(ConstructionInstance{definition:d.id,position_mm:p,health:100});true}}
pub const HOUSE:ConstructionDefinition=ConstructionDefinition{id:"house",cost:ResourceCost{wood:100,stone:80,metal:20,energy:0},width_mm:8000,depth_mm:6000,height_mm:3000,required_technology:Some("construction")};
pub const WORKSHOP:ConstructionDefinition=ConstructionDefinition{id:"workshop",cost:ResourceCost{wood:120,stone:100,metal:80,energy:20},width_mm:10000,depth_mm:8000,height_mm:4000,required_technology:Some("construction")};
#[cfg(test)]mod tests{use super::*;#[test]fn costs_are_checked(){let mut s=ResourceStock{wood:150,stone:100,metal:30,energy:0};assert!(s.spend(ResourceCost{wood:100,stone:50,metal:20,energy:0}));assert_eq!(s.wood,50);assert!(!s.spend(ResourceCost{wood:100,stone:0,metal:0,energy:0}));}#[test]fn construction_requires_technology(){let mut site=ConstructionSite::default();let mut s=ResourceStock{wood:200,stone:200,metal:100,energy:0};assert!(!site.build(HOUSE,[0,0,0],&mut s,&[]));assert!(site.build(HOUSE,[0,0,0],&mut s,&["construction"]));}#[test]fn invalid_position_is_rejected(){let mut site=ConstructionSite::default();let mut s=ResourceStock{wood:200,stone:200,metal:100,energy:0};assert!(!site.build(HOUSE,[-1,0,0],&mut s,&["construction"]));}}
