//! Deterministic technology progression and furniture placement foundations.
#[derive(Clone,Copy,Debug,PartialEq,Eq,PartialOrd,Ord)] pub enum TechnologyTier{Primitive,Stone,Bronze,Iron,Industrial,Modern,Digital,Futuristic}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum TechnologyCategory{Agriculture,Construction,Energy,Manufacturing,Computing,Transportation,Medicine,Communication,Defense,Household}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub struct TechnologyDefinition{pub id:&'static str,pub category:TechnologyCategory,pub tier:TechnologyTier,pub research_cost:u32,pub prerequisites:&'static[&'static str]}
#[derive(Clone,Debug,Default,PartialEq,Eq)] pub struct TechnologyTree{researched:Vec<&'static str>}
impl TechnologyTree{pub fn research(&mut self,tech:TechnologyDefinition)->bool{if self.researched.contains(&tech.id)||tech.prerequisites.iter().any(|p|!self.researched.contains(p)){return false}self.researched.push(tech.id);self.researched.sort_unstable();true}pub fn researched(&self,id:&str)->bool{self.researched.binary_search(&id).is_ok()}pub fn count(&self)->usize{self.researched.len()}}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum FurnitureKind{Chair,Table,Bed,Storage,Desk,Shelf,Cabinet,Workbench,Kitchen,Lighting,Decoration,Sanitary}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub struct FurnitureDefinition{pub id:&'static str,pub kind:FurnitureKind,pub width_mm:u32,pub depth_mm:u32,pub height_mm:u32,pub comfort:u16,pub storage:u32,pub required_technology:Option<&'static str>}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub struct FurnitureInstance{pub definition:&'static str,pub position_mm:[i32;3],pub rotation_quarter_turns:u8,pub durability:u16}
impl FurnitureInstance{pub fn new(definition:&'static str,position_mm:[i32;3])->Self{Self{definition,position_mm,rotation_quarter_turns:0,durability:100}}pub fn rotate(&mut self){self.rotation_quarter_turns=(self.rotation_quarter_turns+1)%4}}
#[derive(Clone,Debug,PartialEq,Eq)] pub struct FurnitureRoom{pub width_mm:u32,pub depth_mm:u32,pub items:Vec<FurnitureInstance>}
impl FurnitureRoom{pub fn new(width_mm:u32,depth_mm:u32)->Self{Self{width_mm,depth_mm,items:Vec::new()}}pub fn place(&mut self,item:FurnitureInstance)->bool{let x=item.position_mm[0];let z=item.position_mm[2];if x<0||z<0||x as u32>self.width_mm||z as u32>self.depth_mm{return false}self.items.push(item);true}}
pub const AGRICULTURE:TechnologyDefinition=TechnologyDefinition{id:"agriculture",category:TechnologyCategory::Agriculture,tier:TechnologyTier::Stone,research_cost:10,prerequisites:&[]};
pub const CONSTRUCTION:TechnologyDefinition=TechnologyDefinition{id:"construction",category:TechnologyCategory::Construction,tier:TechnologyTier::Stone,research_cost:10,prerequisites:&[]};
pub const ELECTRICITY:TechnologyDefinition=TechnologyDefinition{id:"electricity",category:TechnologyCategory::Energy,tier:TechnologyTier::Industrial,research_cost:100,prerequisites:&["construction"]};
pub const COMPUTING:TechnologyDefinition=TechnologyDefinition{id:"computing",category:TechnologyCategory::Computing,tier:TechnologyTier::Digital,research_cost:250,prerequisites:&["electricity"]};
pub const CHAIR:FurnitureDefinition=FurnitureDefinition{id:"chair",kind:FurnitureKind::Chair,width_mm:500,depth_mm:500,height_mm:900,comfort:40,storage:0,required_technology:None};
pub const TABLE:FurnitureDefinition=FurnitureDefinition{id:"table",kind:FurnitureKind::Table,width_mm:1200,depth_mm:700,height_mm:750,comfort:20,storage:0,required_technology:Some("construction")};
pub const BED:FurnitureDefinition=FurnitureDefinition{id:"bed",kind:FurnitureKind::Bed,width_mm:2000,depth_mm:1000,height_mm:600,comfort:100,storage:0,required_technology:Some("construction")};
pub const CABINET:FurnitureDefinition=FurnitureDefinition{id:"cabinet",kind:FurnitureKind::Cabinet,width_mm:900,depth_mm:450,height_mm:2000,comfort:0,storage:120,required_technology:Some("construction")};
#[cfg(test)]mod tests{use super::*;#[test]fn prerequisites_are_enforced(){let mut t=TechnologyTree::default();assert!(!t.research(ELECTRICITY));assert!(t.research(CONSTRUCTION));assert!(t.research(ELECTRICITY));}#[test]fn duplicate_research_is_rejected(){let mut t=TechnologyTree::default();assert!(t.research(AGRICULTURE));assert!(!t.research(AGRICULTURE));assert_eq!(t.count(),1)}#[test]fn furniture_room_bounds_are_enforced(){let mut r=FurnitureRoom::new(2000,2000);assert!(r.place(FurnitureInstance::new("chair",[100,0,100])));assert!(!r.place(FurnitureInstance::new("chair",[2100,0,100])))}#[test]fn furniture_rotation_is_deterministic(){let mut f=FurnitureInstance::new("chair",[0,0,0]);f.rotate();f.rotate();assert_eq!(f.rotation_quarter_turns,2)}}
