#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Particle { pub position:[f32;3], pub velocity:[f32;3], pub density:f32, pub pressure:f32, pub mass:f32 }
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ParticleConfig { pub smoothing_radius:f32, pub rest_density:f32, pub stiffness:f32, pub viscosity:f32 }
impl Default for ParticleConfig{fn default()->Self{Self{smoothing_radius:1.0,rest_density:1000.0,stiffness:20.0,viscosity:0.1}}}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum ParticleError{InvalidConfig,NonFinite}
#[derive(Clone,Debug)]pub struct SphSystem{pub config:ParticleConfig,pub particles:Vec<Particle>}
impl ParticleConfig{pub fn validate(&self)->bool{self.smoothing_radius.is_finite()&&self.smoothing_radius>0.0&&self.rest_density.is_finite()&&self.rest_density>0.0&&self.stiffness.is_finite()&&self.stiffness>=0.0&&self.viscosity.is_finite()&&self.viscosity>=0.0}}
impl SphSystem{pub fn new(config:ParticleConfig)->Result<Self,ParticleError>{if !config.validate(){return Err(ParticleError::InvalidConfig)}Ok(Self{config,particles:Vec::new()})}pub fn add(&mut self,p:Particle)->Result<(),ParticleError>{if !p.position.iter().chain(p.velocity.iter()).all(|v|v.is_finite())||!p.mass.is_finite()||p.mass<0.0{return Err(ParticleError::NonFinite)}self.particles.push(p);self.particles.sort_by(|a,b|a.position.partial_cmp(&b.position).unwrap_or(core::cmp::Ordering::Equal));Ok(())}pub fn step(&mut self,dt:f32,gravity:[f32;3])->Result<(),ParticleError>{if !dt.is_finite()||dt<0.0||!gravity.iter().all(|v|v.is_finite()){return Err(ParticleError::NonFinite)}let r2=self.config.smoothing_radius*self.config.smoothing_radius;for i in 0..self.particles.len(){let mut density=0.0;for j in 0..self.particles.len(){let d2=dist2(self.particles[i].position,self.particles[j].position);if d2<=r2{density+=self.particles[j].mass;}}self.particles[i].density=density.max(f32::EPSILON);self.particles[i].pressure=(density-self.config.rest_density).max(0.0)*self.config.stiffness;for a in 0..3{self.particles[i].velocity[a]+=gravity[a]*dt;}self.particles[i].position=add(self.particles[i].position,mul(self.particles[i].velocity,dt));}Ok(())}}
fn dist2(a:[f32;3],b:[f32;3])->f32{(a[0]-b[0]).powi(2)+(a[1]-b[1]).powi(2)+(a[2]-b[2]).powi(2)}fn add(a:[f32;3],b:[f32;3])->[f32;3]{[a[0]+b[0],a[1]+b[1],a[2]+b[2]]}fn mul(a:[f32;3],s:f32)->[f32;3]{[a[0]*s,a[1]*s,a[2]*s]}
#[derive(Clone,Copy,Debug,PartialEq)]pub enum ParticleMethod{Flip,Pic}
#[derive(Clone,Debug)]pub struct FlipPicGrid{pub width:usize,pub height:usize,pub depth:usize,pub cell_size:f32,pub velocity:Vec<[f32;3]>}
impl FlipPicGrid{pub fn new(width:usize,height:usize,depth:usize,cell_size:f32)->Result<Self,ParticleError>{if width==0||height==0||depth==0||!cell_size.is_finite()||cell_size<=0.0{return Err(ParticleError::InvalidConfig)}Ok(Self{width,height,depth,cell_size,velocity:vec![[0.0;3];width*height*depth]})}fn index(&self,x:usize,y:usize,z:usize)->Option<usize>{if x<self.width&&y<self.height&&z<self.depth{Some((y*self.depth+z)*self.width+x)}else{None}}pub fn set_velocity(&mut self,x:usize,y:usize,z:usize,v:[f32;3])->Result<(),ParticleError>{if !v.iter().all(|x|x.is_finite()){return Err(ParticleError::NonFinite)}let i=self.index(x,y,z).ok_or(ParticleError::InvalidConfig)?;self.velocity[i]=v;Ok(())}pub fn transfer(&self,p:&Particle,method:ParticleMethod)->[f32;3]{let gx=(p.position[0]/self.cell_size).floor().max(0.0) as usize;let gy=(p.position[1]/self.cell_size).floor().max(0.0) as usize;let gz=(p.position[2]/self.cell_size).floor().max(0.0) as usize;let v=self.index(gx,gy,gz).map(|i|self.velocity[i]).unwrap_or([0.0;3]);match method{ParticleMethod::Pic=>v,ParticleMethod::Flip=>[p.velocity[0]+v[0],p.velocity[1]+v[1],p.velocity[2]+v[2]]}}}
#[cfg(test)]mod tests{use super::*;#[test]fn sph_is_deterministic(){let c=ParticleConfig::default();let mut a=SphSystem::new(c).unwrap();let mut b=SphSystem::new(c).unwrap();let p=Particle{position:[0.0,0.0,0.0],velocity:[0.0;3],density:0.0,pressure:0.0,mass:1.0};a.add(p).unwrap();b.add(p).unwrap();a.step(1.0/60.0,[0.0,-9.81,0.0]).unwrap();b.step(1.0/60.0,[0.0,-9.81,0.0]).unwrap();assert_eq!(a.particles,b.particles);}#[test]fn pic_reads_grid_velocity(){let mut g=FlipPicGrid::new(2,2,2,1.0).unwrap();g.set_velocity(0,0,0,[1.0,2.0,3.0]).unwrap();let p=Particle{position:[0.1,0.1,0.1],velocity:[0.0;3],density:1.0,pressure:0.0,mass:1.0};assert_eq!(g.transfer(&p,ParticleMethod::Pic),[1.0,2.0,3.0]);}}